name: DonutRtp
version: '1.0'
main: Kai.donutRtp.DonutRtp
api-version: '1.21'
author: [ C0dingKai ]
website: github.com/C0dingKai
commands:
  rtp:
    description: Teleports you randomly
    usage: /rtp

